### ISSUE TITLE
Issue pasting into Guac GUI

### ISSUE THREAD

**Issue by xthursdayx** [linuxserver/docker-baseimage-gui#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Ideally I would like to be able to copy text  and paste into the program being accessed via the Guacamole GUI. 

## Current Behavior

I created a gPodder podcatcher docker image using this base image. If you try to copy text, such as a podcast RSS feed, and paste it into the gPodder 'add feed' section, nothing happens.

## Steps to Reproduce

1. Build my [docker container](https://github.com/xthursdayx/gpodder-docker)
2. Find a podcast RSS feed on your normal browser and copy it. 
3. Try to paste the RSS feed address into the 'add feed url' menu in gPodder

## Environment
**OS:** - Docker host=unRAID. GUI accessed via MacOS
**CPU architecture:** x86_64      
**How docker service was installed:**      

`FROM lsiobase/guacgui`
Full Dockerfile can be seen here: https://github.com/xthursdayx/gpodder-docker/blob/master/Dockerfile

## Command used to create docker container (run/create/compose/screenshot)

`docker create --name='gPodder' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'GUAC_USER'='admin' -e 'GUAC_PASS'='*********' -e 'TZ'='America/New_York' -e 'WIDTH'='1280' -e 'HEIGHT'='720' -p '3389:3389/tcp' -p '8383:8080/tcp' -v '/mnt/user/Media/Podcasts/':'/downloads':'rw,slave' -v '/mnt/cache/appdata/gPodder':'/config':'rw' 'xthursdayx/gpodder-docker'`

## Docker logs

These would be the logs of my gPodder container, so I don't think they would be useful here. 

## Other information. 
I believe that this may be related to the issues discussed here, but I don't know enough about Guacamole to be positive: [https://sourceforge.net/p/guacamole/discussion/1110834/thread/3ffa2bb2/
](https://sourceforge.net/p/guacamole/discussion/1110834/thread/3ffa2bb2/
)

**Comment by aptalca** [comment]
Ctrl+Alt+Shift opens the menu that allows you to control clipboard

Also check the site settings (in chrome) to enable clipboard access for the url

**Comment by xthursdayx** [comment]
Ah, okay, thanks for that. 

Ctrl+CMD+Shift works on MacOS, however it only seems to work in Chromium-based browsers, not Firefox.
